export const REQUEST_STUDENTS = 'REQUEST_STUDENTS';
export const RECEIVE_STUDENTS = 'RECEIVE_STUDENTS';
export const SET_FILTER_PARAMS = 'SET_FILTER_PARAMS';
export const CLEAR_FILTER_PARAMS = 'CLEAR_FILTER_PARAMS';
export const ERROR_RECEIVE_STUDENTS = 'ERROR_RECEIVE_STUDENTS';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const SUCCESS_DELETE_STUDENT = 'SUCCESS_DELETE_STUDENT';
export const ERROR_DELETE_STUDENT = 'ERROR_DELETE_STUDENT';
